test: clean
	bundle exec ruby main.rb surfer
	bundle exec ruby main.rb arch horizontal
clean:
	rm -f *-energy.jpg *-energy-*.jpg \
	*-highlighted.jpg *-highlighted-*.jpg \
	*-cropped.jpg *-cropped-*.jpg
